name: CI - Test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Npm Dependencies
        run: npm ci

      - name: Build App
        run: npm run build

      - name: Run tests with jest
        run: npm run test

      - name: Cypress.io
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          wait-on: "http://localhost:3000"
